// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Chat struct {
	ID           int64
	Command      string
	Step         int64
	Data         []byte
	ReplyMarkup1 []byte
	ReplyMarkup2 []byte
	ReplyMarkup3 []byte
	ReplyMarkup4 []byte
}

type PrepaidProduct struct {
	ID                  int64
	Name                string
	Category            string
	Brand               string
	Type                string
	SellerName          string
	Price               int64
	BuyerSkuCode        string
	BuyerProductStatus  bool
	SellerProductStatus bool
	UnlimitedStock      bool
	Stock               int64
	Multi               bool
	StartCutOff         *string
	EndCutOff           *string
	Description         *string
}

type User struct {
	ID        int64
	Username  *string
	FirstName *string
	LastName  *string
	CreatedAt sql.NullTime
}
